name: Run demoblaze test on staging environment
on:
  push:
    branches:
      - feature/CreateMyFirstAction

jobs:
  execute-test:
    name: Execute test Automated
    runs-on: [ self-hosted ]

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date + '%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache gradle dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-dependencies-${{ steps.date.outputs.date }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk




